name: test

on: [push, pull_request]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.4']
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2.32.0
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Run tests with coverage
        run: vendor/bin/phpunit --coverage-text
